import { expect, it } from "vitest";
import {
  validateVenuePrivateGeneratedImage,
  validateVenuePrivateGeneratedImageFile,
} from "./venue-private-image";

const jpeg = new Uint8Array([0xff, 0xd8, 0xff, 0x00]);
const png = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
const webp = new Uint8Array([
  0x52, 0x49, 0x46, 0x46, 0x00, 0x00, 0x00, 0x00, 0x57, 0x45, 0x42, 0x50,
]);

it.each([
  ["image/jpeg", jpeg],
  ["image/png", png],
  ["image/webp", webp],
] as const)(
  "accepts supported %s bytes without a filename",
  (mimeType, bytes) => {
    expect(
      validateVenuePrivateGeneratedImage({
        mimeType,
        bytes,
        widthPx: 320,
        heightPx: 180,
      }),
    ).toEqual({
      ok: true,
      value: {
        mimeType,
        sizeBytes: bytes.byteLength,
        widthPx: 320,
        heightPx: 180,
      },
    });
  },
);

it("rejects an unsupported MIME or mismatched magic bytes", () => {
  expect(
    validateVenuePrivateGeneratedImageFile({
      mimeType: "image/gif",
      bytes: jpeg,
    }),
  ).toEqual({ ok: false, error: "unsupported_type" });
  expect(
    validateVenuePrivateGeneratedImageFile({
      mimeType: "image/png",
      bytes: jpeg,
    }),
  ).toEqual({ ok: false, error: "unsupported_type" });
  expect(
    validateVenuePrivateGeneratedImage({
      mimeType: "image/png",
      bytes: jpeg,
      widthPx: 320,
      heightPx: 180,
    }),
  ).toEqual({ ok: false, error: "unsupported_type" });
});

it("enforces generated byte-size boundaries", () => {
  expect(
    validateVenuePrivateGeneratedImageFile({
      mimeType: "image/jpeg",
      bytes: new Uint8Array(),
    }),
  ).toEqual({ ok: false, error: "invalid_size" });
});

it("enforces the same decoded dimension bounds as originals", () => {
  expect(
    validateVenuePrivateGeneratedImage({
      mimeType: "image/jpeg",
      bytes: jpeg,
      widthPx: 0,
      heightPx: 180,
    }),
  ).toEqual({ ok: false, error: "invalid_dimensions" });
});
